name: Publish on PyPI

on:
  push:
    tags: '*'

jobs:

  pypi-publishing:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build wheels
      uses: pypa/cibuildwheel@v2

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
