name: Publish on PyPI

on:
  push:
    tags: '*'

jobs:

  pypi-publishing:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install wheel
      run: |
        python3 -m pip install --upgrade pip wheel

    - name: Prepare wheel distribution
      run: pip wheel --no-deps --wheels-dir=dist .

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
