# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:

  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        py: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.py }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py }}
    - name: Install Tox
      run: |
        pip install tox
    - name: Run test environments
      env:
        TOX_SKIP_ENV: "^((?!py${{ matrix.py }}).)*$"
      run: |
        tox

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install Tox and any other packages
      run: |
        pip install tox
    - name: Run linters
      run: |
        tox -e linters
