# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Tox
      run: |
        pip install tox
    - name: Run test environments
      run: |
        tox -e py${{ matrix.python-version }}-pytest5-trytond5,py${{ matrix.python-version }}-pytest6-trytond5,py${{ matrix.python-version }}-pytest5-trytond6,py${{ matrix.python-version }}-pytest6-trytond6,py${{ matrix.python-version }}-pytest5-trytonddev,py${{ matrix.python-version }}-pytest6-trytonddev,

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Tox and any other packages
      run: |
        pip install tox
    - name: Run linters
      run: |
        tox -e linters
